# Generated by Django 5.2.5 on 2026-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itineraryitem',
            constraint=models.UniqueConstraint(fields=('itinerary', 'date', 'order'), name='unique_itinerary_item_order_per_date'),
        ),
    ]
