# Generated by Django 5.2.5 on 2026-08-14 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('travel_style', models.CharField(choices=[('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('adventurous', 'Adventurous')], default='balanced', max_length=20)),
                ('accommodation', models.CharField(blank=True, choices=[('budget', 'Budget'), ('mid_range', 'Mid-range'), ('luxury', 'Luxury')], max_length=20, null=True)),
                ('pace', models.CharField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='trip_preferences', to='trips.interest')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_preferences',
            },
        ),
    ]
